### ISSUE TITLE
keepassxc 2.6.6

### ISSUE THREAD

**Issue by denydias** [conraid/SlackBuilds#11]
Hello! First and foremost, thank you so much for this great repository, @conraid. You've certainly raised the bar of Slackware packaging game.

I don know it this is the preferred way to do this, but here I go... keepassxc has been [upgraded to 2.6.6](https://github.com/keepassxreboot/keepassxc/releases/tag/2.6.6).

Thank you so much.

**Comment by conraid** [comment]
Thanks for the tip.
I check for updates with nvchecker, and in the case of software on github also with notifications from github, but of course I don't always manage to do it right away. 
It will be updated in the next commit, thanks again.

I'm sorry for my bad english

**Comment by denydias** [comment]
Nice, @conraid! The updated package is already available. Don't bother with the english. We just need enough to communicate.

Thank you again.
