### ISSUE TITLE
broken symlinks

### ISSUE THREAD

**Issue by maravtdm** [conraid/SlackBuilds#13]
In /usr/lib64/ :
```
liblua.a
liblua.so -> liblua.so.5.4.3
liblua.so.5.4 -> liblua.so.5.4.3
liblua.so.5.4.3
liblua5.4.so -> /usr/lib/liblua.so.5.4.3

```
but /usr/lib/liblua.so.5.4.3 doesn't exist

**Comment by maravtdm** [comment]
```
/usr/bin/x264 -> x264-8bit
/usr/bin/x264-10
/usr/bin/x264-8
```
x264-8bit doesn't exist

**Comment by maravtdm** [comment]
> In /usr/lib64/ :
> 
> ```
> liblua.a
> liblua.so -> liblua.so.5.4.3
> liblua.so.5.4 -> liblua.so.5.4.3
> liblua.so.5.4.3
> liblua5.4.so -> /usr/lib/liblua.so.5.4.3
> ```
> 
> but /usr/lib/liblua.so.5.4.3 doesn't exist

Suggestion for the slackbuild
```
--- lua.SlackBuild.1    2022-04-17 13:18:57.596342417 +0200
+++ lua.SlackBuild      2022-04-17 13:19:27.143401139 +0200
@@ -110,7 +110,7 @@
 linux install
 
 # Make symlink like 5.2 and 5.1 legacy packages
-ln -sf /usr/lib/liblua.so.$VERSION $PKG/usr/lib${LIBDIRSUFFIX}/liblua${MAINVERSION}.so
+ln -sf /usr/lib${LIBDIRSUFFIX}/liblua.so.$VERSION $PKG/usr/lib${LIBDIRSUFFIX}/liblua${MAINVERSION}.so
 
 # Install the pkg-config file so other apps can find LUA
 mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig
```

**Comment by maravtdm** [comment]
> ```
> /usr/bin/x264 -> x264-8bit
> /usr/bin/x264-10
> /usr/bin/x264-8
> ```
> 
> x264-8bit doesn't exist
> 
> line 112 in the SlackBuild: `ln -s x264-8bit $PKG/usr/bin/x264`

```
--- x264.SlackBuild.1   2022-04-17 13:25:47.698694583 +0200
+++ x264.SlackBuild     2022-04-17 13:26:17.598804672 +0200
@@ -109,7 +109,7 @@
   cd ..
 done
 
-ln -s x264-8bit $PKG/usr/bin/x264
+ln -s x264-8 $PKG/usr/bin/x264
 
 # Don't ship .la files:
 rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
```

**Comment by maravtdm** [comment]
**x264-8bit** still exists

**Comment by conraid** [comment]
I'm sorry for this huge delay, but I don't receive notifications or emails. I will check manually in the future.

Oops, my mistake, next changelog there will be corrected version. Thank you very much
