### ISSUE TITLE
Wrong PG_VERSION

### ISSUE THREAD

**Issue by dct** [conraid/SlackBuilds#16]
https://github.com/conraid/SlackBuilds/blob/4338e3a0060bd796db0e6d8a9a82b19aa185efda/postgresql/postgresql.SlackBuild#L48

Should be 14 instead of 13

**Comment by conraid** [comment]
I'm sorry for this huge delay, but I don't receive notifications or emails. I will check manually in the future.

Now is:
`PG_VERSION=$(echo $VERSION | cut -d. -f1)`
