### ISSUE TITLE
Last php-xdebug broken with extra/php81-8.1.8

### ISSUE THREAD

**Issue by denydias** [conraid/SlackBuilds#18]
Hi there!

`Mon, 11 Jul 2022 09:29:08 UTC` broke php-xdebug compatibility with stock extra/php81-8.1.8-x86_64-1. Now it prints:

```
$ php --version
Xdebug requires Zend Engine API version 320190902.
The Zend Engine API version 420210902 which is installed, is newer.
Contact Derick Rethans at https://xdebug.org/docs/faq#api for a later version of Xdebug.
```

This happens because:

```
Reuilt all php packages against php-7.4.30.
```

But `Tue, 14 Jun 2022 09:05:38 UTC` changelog was fine with extra/php version then:

```
php-xdebug-3.1.5-x86_64-2cf.txz:  Rebuilt.
	- Recompiled against php81-8.1.7.
```

Have you dropped support to `extra/php` on your php extensions?

**Comment by conraid** [comment]
I'm sorry for this huge delay, but I don't receive notifications or emails. I will check manually in the future.

Now php is only in main repository, before I compiled according to my needs, and with php I sometimes made some confusion. Pardon
