### ISSUE TITLE
audit doinst.sh errors

### ISSUE THREAD

**Issue by bobbintb** [conraid/SlackBuilds#26]
The doinst.sh script for the audit package has errors. I get this when installing:

`Executing install script for audit-4.0.1-x86_64-2cf.txz.
main: line 5: [: too many arguments
cat: 'etc/audit/plugins.d/*.new': No such file or directory
cat: etc/audit/zos-remote.conf.new: No such file or directory
cat: etc/audit/audisp-remote.conf.new: No such file or directory
cat: etc/audit/audit-stop.rules.new: No such file or directory
cat: etc/audit/auditd.conf.new: No such file or directory
mv: cannot stat 'etc/sysconfig/auditd': No such file or directory
cat: etc/libaudit.conf.new: No such file or directory`

I haven't really worked with the package yet so I don't know what effect it has. I don't know what the issue is with line 5 but the others are obviously missing the forward slash at the beginning.

**Comment by conraid** [comment]
Thank you. I fixed. It will be available at the next commit.
