### ISSUE TITLE
Enable TPM emulation in QEMU

### ISSUE THREAD

**Issue by drigoskalwalker** [conraid/SlackBuilds#27]
As the title says, you already have swtpm in your repository.
Just enable TPM in the SlackBuild please.

Thank you for your job.

**Comment by conraid** [comment]
I had not voluntarily enabled it; I have never been a big fan of TPM. But I will enable it if needed. It will be available with the next commit. Please do a test if everything is ok.

**Comment by drigoskalwalker** [comment]
Thank you, now it's possible to run Windows 11 on that!
