### ISSUE TITLE
Enable QEMU optimizations

### ISSUE THREAD

**Issue by drigoskalwalker** [conraid/SlackBuilds#32]
Hi, sorry to reach you again.
Would you mind to enable theses optimizations?

  --enable-avx2
  --enable-avx512bw
  --enable-avx512f

I found out that my compiled QEMU improved performance with them.

**Comment by conraid** [comment]
Okay, I compiled and it works. But not having a cpu that supports such optimizations, I can't do extensive testing.
Let me know by email, thanks.

**Comment by drigoskalwalker** [comment]
My CPU only supports AVX2 and I got much more performance with these optimizations, but I think those are only used if available.
