### ISSUE TITLE
Update flatpak slack-required

### ISSUE THREAD

**Issue by denydias** [conraid/SlackBuilds#34]
There are more required packages in flatpak's slack-required:

```
xdg-desktop-portal-gtk
bubblewrap
ostree
appstream-glib
appstream
libxmlb
snowball
```

libxmlb and snowball must be added.

**Comment by denydias** [comment]
I totally forgot the cascading fashion of slack-required. My bad! I'll just close this and sorry for the noise.

**Comment by conraid** [comment]
No problem. However, I'll see if I can add them in the next update to avoid misunderstandings.
