### ISSUE TITLE
v4.0.2 of auditd is broken, unable to add rules

### ISSUE THREAD

**Issue by bobbintb** [conraid/SlackBuilds#35]
The current (4.0.2) build of auditd is broken for Arch Linux, as it is unable to add rules. I just updated and it appears Slackware has the issue as well. Here is more information:
https://bbs.archlinux.org/viewtopic.php?id=298837

Related to this, the slackers repo doesn't have previous versions. Not that I could find anyhow. I thought I had kept the previous package version but I guess I didn't. Are previous build archived somewhere?

**Comment by conraid** [comment]
Yes, I saw. Considering that on the audit site they still give 4.0.1 among the stable versions, I downgraded. The next commit will be there. Let me know if everything is OK.
Thanks for the report and sorry for the bad English.

**Comment by conraid** [comment]
I have updated again by applying the patch that solves this bug.
