### ISSUE TITLE
Virt-Manager update.

### ISSUE THREAD

**Issue by drigoskalwalker** [conraid/SlackBuilds#39]
Can you please update virt-manager to version 5?
I will appreciate.
Thank you.

**Comment by conraid** [comment]
I am working on it, unfortunately it requires pylint and related dependencies, I have to build all the packages.
Also I would have no way to test it currently, if you tell me though that you can do it, as soon as I can I will get to building all the new dependencies.

**Comment by drigoskalwalker** [comment]
Sure, if you can upload the updated SlackBuild I can work on it

**Comment by drigoskalwalker** [comment]
You are great!
I did the upgrade and seems that virt-manager 5 is running fine.
I cannot create or manage any virtual machine yet cause the image mirros are really  slow today.
But I will leave my feedback.
Thanks for now

**Comment by drigoskalwalker** [comment]
Hi
Finally I manage to try, it was my wifi sorry.
Man, you really did a great job!
Everything is working like a charm
and it's really fast!
Really thank you.
