### ISSUE TITLE
Found some errors in the slackbuild that prevent building.

### ISSUE THREAD

**Issue by technetos** [conraid/SlackBuilds#4]
[tar command](https://github.com/conraid/SlackBuilds/blob/master/libuv/libuv.SlackBuild#L68)
`tar xvf $CWD/$PKGNAM-$VERSION.tar.gz || tar xvf $CWD/v${VERSION}.tar.gz || tar xvf $CWD/$PKGNAM-v$VERSION.tar.gz`

[cd into directory](https://github.com/conraid/SlackBuilds/blob/master/libuv/libuv.SlackBuild#L69)
`cd $PKGNAM-v$VERSION`

[docdir configure param](https://github.com/conraid/SlackBuilds/blob/master/libuv/libuv.SlackBuild#L84)
`--docdir=/usr/doc/$PKGNAM-v$VERSION \`

[make doc directory](https://github.com/conraid/SlackBuilds/blob/master/libuv/libuv.SlackBuild#L99)
`mkdir -p $PKG/usr/doc/$PKGNAM-v$VERSION`

[copy docs](https://github.com/conraid/SlackBuilds/blob/master/libuv/libuv.SlackBuild#L100)
`cp -a $DOCFILES $PKG/usr/doc/$PKGNAM-v$VERSION || true`

[store a copy of the slackbuild](https://github.com/conraid/SlackBuilds/blob/master/libuv/libuv.SlackBuild#L101)
`cat $CWD/$PKGNAM.SlackBuild > $PKG/usr/doc/$PKGNAM-v$VERSION/$PKGNAM.SlackBuild`

[makepkg](https://github.com/conraid/SlackBuilds/blob/master/libuv/libuv.SlackBuild#L107)
`/sbin/makepkg -l y -c n $OUTPUT/$PKGNAM-v$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}`

**Comment by conraid** [comment]
No, v$VERSION is the version of the file downloaded from github, but then the directory within is no "v".
Also if you use eg. "wget --content-disposition", or browser download, name is directly libuv-$VERSION.tar.gz

The script works, both with libuv-$VERSION, both with v$VERSION, no need to change anything else.



I apologize for my bad English.

**Comment by technetos** [comment]
Okay, my bad.  Glad to know that the existing version does indeed work. :)
