### ISSUE TITLE
lynis.SlackBuild - bash_completion.d wrong /path

### ISSUE THREAD

**Issue by Geyup** [conraid/SlackBuilds#5]
Just wanted to point out in your lynis.SlackBuild line 72 is not correct;

install -Dm644 extras/bash_completion.d/lynis $PKG/etc/bash_completion.d/lynis

This is correct /path;

install -Dm644 extras/bash_completion.d/lynis $PKG/usr/share/bash-completion/completions/lynis

At least this is correct for Slackware 14.2, not sure if 14.1 also uses the same /path for /usr/share...

**Comment by conraid** [comment]
I'm sorry, I see now this issue.
/etc/bash_completion.d is path for  third-party packages. Also libreoffice by Alien Bob or packages in slackbuilds.org use /etc/bash_completion.d
It is best to leave /usr to packages by Pat
